/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio2;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LuisFernando
 */
public class Ventana extends javax.swing.JFrame {
PasarAnimales p = new PasarAnimales();
PasarInformacion i = new PasarInformacion();
Buscar b;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMostar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        carga = new javax.swing.JProgressBar();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacion = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscador De Animales");

        btnBuscar.setBackground(new java.awt.Color(102, 102, 255));
        btnBuscar.setForeground(new java.awt.Color(51, 0, 51));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        carga.setBackground(new java.awt.Color(0, 0, 255));
        carga.setForeground(new java.awt.Color(51, 51, 255));
        carga.setStringPainted(true);

        txtInformacion.setEditable(false);
        txtInformacion.setColumns(20);
        txtInformacion.setRows(5);
        jScrollPane1.setViewportView(txtInformacion);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(carga, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(txtBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnLimpiar)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jMostar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(jMostar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombre=txtBuscar.getText();
        b=new Buscar(nombre);
        i.cargarDocumento(b);
        txtInformacion.setText(i.getMensaje());
        switch(b.NombrarAnimal()){
             case "Lobo":
                 carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirLobo()));
             break;
             case "lobo":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirLobo()));
             break;
             case "Perro":
                 carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirPerro()));
             break;
             case "perro":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirPerro()));
             break;
             case "Zorro":
                 carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirZorro()));
             break;
             case "zorro":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirZorro()));
             break;
             case "Gato":
                 carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirGato()));
             break;
             case "gato":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirGato()));
             break;
             case "Hormiga":
                 carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirHormiga()));
             break;
             case "hormiga":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirHormiga()));
             break;
             case "Leon":
                 carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirLeon()));
             break;
             case "leon":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirLeon()));
             break;
            case "Peña":
                carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirPeña()));
             break;
             case "peña":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirPeña()));
             break;
              case "Jirafa":
                  carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirJirafa()));
             break;
             case "jirafa":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirJirafa()));
             break;
              case "Pato":
                  carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirPato()));
             break;
             case "pato":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirPato()));
             break;
              case "Burro":
                  carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirBurro()));
             break;
             case "burro":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirBurro()));
             break;
             case "Humano":
                 carga.setValue(100);
                 jMostar.setIcon(new ImageIcon(p.introducirHumano()));
             break;
             case "humano":
                 carga.setValue(100);
                  jMostar.setIcon(new ImageIcon(p.introducirHumano()));
             break;
             default:
                 JOptionPane.showMessageDialog(null, "¡Animal : "+b.NombrarAnimal()+" no encontrado!");
             break;
             
       }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtInformacion.setText("");
        txtBuscar.setText("");
        jMostar.setIcon(null);
        i.destruir();
        b.destruir();
        p.destruir();
    }//GEN-LAST:event_btnLimpiarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JProgressBar carga;
    private javax.swing.JLabel jMostar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtInformacion;
    // End of variables declaration//GEN-END:variables
}
